export { default as CameraIcon } from './Camera'
export { default as DownIcon } from './Download'
export { default as MailIcon } from './Mail'
export { default as PhoneIcon } from './Phone'
export { default as FontSizeIcon } from './FontSize'
export { default as PaletteIcon } from './Palette'
export { default as TextDocumentIcon } from './TextDocument'
export { default as EarthIcon } from './Earth'
